models/librodiario.py
from utils.db import db


class Libro(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    total_ganado = db.Column(db.DECIMAL(10))
    created_at = db.Column(db.date)

    def __init__(self, id, total_ganado, created_at):
        self.id = id
        self.total_ganado = total_ganado
        self.created_at = created_at

models/menu.py
from utils.db import db


class Menu(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    price = db.Column(db.DECIMAL(4))
    description = db.Column(db.String(200))

    def __init__(self, name, price, description):
        self.name = name
        self.price = price
        self.description = description

models/user.py
from utils.db import db
from werkzeug.security import check_password_hash


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    lastname = db.Column(db.String(100))
    email = db.Column(db.String(100), unique=True)
    phone = db.Column(db.DECIMAL(20))
    username = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(200))

    def __init__(self, name, lastname, email, phone, username, password):
        self.name = name
        self.lastname = lastname
        self.email = email
        self.phone = phone
        self.username = username
        self.password = password

    def check_password(self, password):
        return check_password_hash(self.password, password)

app.py
from flask import Flask
from routes.home import home
from routes.user import user
from routes.menu import menu
from flask_sqlalchemy import SQLAlchemy
from config import DATABSE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = 'secret key'
app.config['SQLALCHEMY_DATABASE_URI'] = DATABSE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(user)
app.register_blueprint(menu)
app.register_blueprint(home)

routes/home.py
from flask import (
    Blueprint, render_template, request, redirect, url_for, flash
)
from werkzeug.security import check_password_hash, generate_password_hash
from utils.db import db

home = Blueprint('home', __name__)


@home.route('/')
def welcome():
    return redirect(url_for('user.login'))


@home.route('/index', methods=['GET', 'POST'])
def go_home():
    if request.method == 'POST':
        return render_template('menu/home.html')
    return render_template('menu/home.html')

routes/menu.py
from flask import (
    Blueprint, render_template, request, redirect, url_for, flash
)
from models.menu import Menu
from utils.db import db

# menu = Blueprint('menu', __name__)
menu = Blueprint('menu', __name__, url_prefix='/menu')


@menu.route('/')
def index():
    # return 'index'
    return redirect(url_for('menu.register_plate'))


@menu.route('/show_plates')
def show_plates():
    menu = Menu.query.all()
    return render_template('/menu/show.html', menu=menu)


@menu.route('/list_menu')
def list_menu():
    menu = Menu.query.all()
    return render_template('/menu/menulist.html', menu=menu)


@menu.route('/register_plate')
def register_plate():
    return render_template('menu/register.html')


@menu.route('/add_plate', methods=['POST'])
def add_plate():
    name = request.form['name']
    price = request.form['price']
    description = request.form['description']
    new_plate = Menu(name, price, description)
    db.session.add(new_plate)
    db.session.commit()
    # flash('Plate added successfully!')
    flash('Plate added successfully!')
    return redirect(url_for('menu.show_plates'))


@menu.route('/update_plate/<id>', methods=['GET', 'POST'])
def update_plate(id):
    update_plate = Menu.query.get(id)
    if request.method == 'POST':
        update_plate.name = request.form['name']
        update_plate.price = request.form['price']
        update_plate.description = request.form['description']
        db.session.commit()
        flash('Plate updated successfully!')
        return redirect(url_for('menu.show_plates'))

    return render_template('menu/update.html', plate=update_plate)


@menu.route('/delete_plate/<id>')
def delete_plate(id):
    delete_plate = Menu.query.get(id)
    db.session.delete(delete_plate)
    db.session.commit()
    flash('Plate deleted successfully!')
    return redirect(url_for('menu.show_plates'))


@menu.route('/about')
def about():
    return render_template('about.html')

routes/user.py
import functools
from flask import (
    Blueprint, render_template, request, redirect, url_for, flash, session
)
from werkzeug.security import check_password_hash, generate_password_hash
from models.user import User
from utils.db import db


user = Blueprint('user', __name__, url_prefix='/auth')
# user = Blueprint('user', __name__)


@user.route('/')
def index():
    return redirect(url_for('user.login'))
    # return 'hola'


@user.route('/login')
def login():
    return render_template('auth/singin.html')


# @user.route('/login', methods=['GET', 'POST'])
# def login():
    # if request.method == 'POST' and 'username' in request.form and 'password' in request.form:
        # username = request.form['username']
        # password = request.form['password']
        # passhash = generate_password_hash(password)
        # user = User.query.filter_by(username=username).first()
        # check_pass = check_password_hash(user.password, password)
        # if passhash == check_pass:
            # flash('Please check your login details and try again.')
            # return redirect(url_for('home.go_home'))
    # if request.method == 'POST':
        # username = request.form['username']
        # password = request.form['password']
        # passhash = generate_password_hash(password)
        # user = User.query.filter_by(username=username).first()
        # pass_db = user.password
        # print(pass_db)
        # if password == passhash:
    # return render_template('auth/singin.html')
 # return redirect(url_for('user.login'))

# @user.route('/login', methods=['GET', 'POST'])
# def login():
    # if request.method == 'POST':
        # # username = request.form['username']
        # # check_user = User.query.filter_by(username=username).first()
        # # return render_template(url_for())
        # return render_template('auth/login.html')
    # else:
        # return render_template('auth/login.html')


@user.route('/register_user')
def register_user():
    return render_template('auth/register.html')


@user.route('/add_user', methods=['POST'])
def add_user():
    if request.method == 'POST':
        name = request.form['name']
        lastname = request.form['lastname']
        email = request.form['email']
        phone = request.form['phone']
        username = request.form['username']
        password = request.form['password']
        new_user = User(name, lastname, email, phone, username, generate_password_hash(password))
        db.session.add(new_user)
        db.session.commit()
        flash('User added successfully!')
        return redirect(url_for('user.login'))
    return 'error'


@user.route('/show_users', methods=['GET', 'POST'])
def show_users():
    user = User.query.all()
    if request.method == 'POST':
        return render_template('/auth/show.html', users=user)
        if request.method == 'GET':
            return render_template('/auth/show.html', users=user)
    return render_template('/auth/show.html', users=user)


@user.route('/update_user/<id>', methods=['GET', 'POST'])
def update_user(id):
    update_user = User.query.get(id)
    if request.method == 'POST':
        update_user.name = request.form['name']
        update_user.lastname = request.form['lastname']
        update_user.email = request.form['email']
        update_user.phone = request.form['phone']
        update_user.username = request.form['username']
        # update_user.password = request.form['password']
        db.session.commit()
        flash('User updated successfully!')
        return redirect(url_for('user.show_users'))
    return render_template('auth/update.html', user=update_user)


@user.route('/delete_user/<id>')
def delete_user(id):
    user_delete = User.query.get(id)
    db.session.delete(user_delete)
    db.session.commit()
    flash('User deleted successfully!')
    return redirect(url_for('user.login'))


@user.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('home.welcome'))

templates/base/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %} - Restaurante</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{{url_for('static', filename='css/login/singin.css')}}" rel="stylesheet">
  </head>
  <body>
    {% block body %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

templates/base/menu.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %} - Restaurante</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main/main.css')}}" >
    <link rel="stylesheet" href="{{url_for('static', filename='css/main/carousel.css')}}" >
  </head>
  <body>
    {% include('partials/menu/_navbar.html') %}
    <div class="container p-2">
      {% block body %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- btn-delete script -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

templates/base/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %} - Restaurante</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main/main.css')}}" >
  </head>
  <body>
    <div class="container p-2">
      {% block body %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- btn-delete script -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

templates/base/user.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %} - Restaurante</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main/main.css')}}" >
  </head>
  <body>
    <div class="container p-2">
      {% block body %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- btn-delete script -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

templates/menu/home.html
{% extends 'base/menu.html' %}

{% block header %}
  <h1>{% block title %}Inicio{% endblock %}</h1>
{% endblock %}

{% block body %}
  {% include 'partials/menu/_corousel.html' %}
{% endblock %}

templates/menu/menulist.html
{% extends 'base/menu.html' %}

{% block header %}
  <h1>{% block title %}Lista Menú {% endblock %}</h1>
{% endblock %}

{% block body %}
  {% include 'partials/messages/_messages.html' %}
  <div class="mb-3">
    <table class="table table-bordered table-hover table-dark table-stripped card-body">
      <thead>
        <tr>
          <th>Nombre del plato</th>
          <th>Descripción</th>
          <th>Precio (Bs.)</th>
        </tr>
      </thead>
      <tbody>
        {% for plate in menu %}
          <tr>
            <td>{{ plate.name }}</td>
            <td>{{ plate.description }}</td>
            <td>{{ plate.price }} <strong>Bs.</strong></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/menu/register.html
{% extends 'base/menu.html' %}

{% block header %}
  <h1>{% block title %}Nuevo Plato {% endblock %}</h1>
{% endblock %}

{% block body %}
  <div class="mb-3">
    {% include 'partials/menu/_menuForm.html' %}
  </div>
{% endblock %}

templates/menu/show.html
{% extends 'base/menu.html' %}

{% block header %}
  <h1>{% block title %}Lista Menú {% endblock %}</h1>
{% endblock %}

{% block body %}
  {% include 'partials/messages/_messages.html' %}
  <div class="mb-3">
    <table class="table table-bordered table-hover table-dark table-stripped card-body">
      <thead>
        <tr>
          <th>Nombre del plato</th>
          <th>Descripción</th>
          <th>Precio (Bs.)</th>
          <th colspan="2">Operationes</th>
        </tr>
      </thead>
      <tbody>
        {% for plate in menu %}
          <tr>
            <td>{{ plate.name }}</td>
            <td>{{ plate.description }}</td>
            <td>{{ plate.price }} <strong>Bs.</strong></td>
            <td>
            <a href="{{ url_for('menu.update_plate', id=plate.id) }}" class="btn btn-warning btn-sm">Editar</a>
            </td>
            <td>
            <a href="{{ url_for('menu.delete_plate', id=plate.id) }}" class="btn btn-danger btn-sm btn-delete">Eliminar</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/menu/update.html
{% extends 'base/menu.html' %}

{% block header %}
  <h1>{% block title %}Editar Plato {% endblock %}</h1>
{% endblock %}

{% block body %}
  <div class="mb-3">
    {% include 'partials/menu/_updateForm.html' %}
  </div>
{% endblock %}

templates/partials/menu/_corousel.html
<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{url_for('static', filename='assets/carousel/add_plate.jpg')}}" class="d-block w-100" >

        <div class="container">
          <div class="carousel-caption text-start">
            <!--<h1>Registrar Plato</h1>-->
            <!--<p>Some representative placeholder content for the first slide of the carousel.</p>-->
            <p><a class="btn btn-lg btn-primary" href="{{url_for('menu.register_plate')}}">Registrar Plato</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{url_for('static', filename='assets/carousel/list_menu.jpg')}}" class="d-block w-100" >

        <div class="container">
          <div class="carousel-caption">
            <!--<h1>Another example headline.</h1>-->
            <!--<p>Some representative placeholder content for the second slide of the carousel.</p>-->
            <p><a class="btn btn-lg btn-primary" href="{{url_for('menu.list_menu')}}">Menu</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><ect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2022 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>

templates/partials/menu/_menuForm.html
<div class="mt-5">
  <form action="{{url_for('menu.add_plate')}}" method="post" class="card" >
    <div class="card-body p-4">
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Nombre de plato</label>
        <input type="text" name="name" placeholder="Write a name plate" class="form-control" id="exampleFormControlInput1 validationDefault01" required />
      </div>
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Precio de plato</label>
        <input type="text" name="price" placeholder="Write a price" class="form-control" id="exampleFormControlInput1 validationDefault05" pattern="[0-9]+" required/>
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Descripción del producto</label>
        <textarea name="description" class="form-control" id="exampleFormControlTextarea1" rows="3" style="background-color: #ECEFF4;" required></textarea>
      </div>
      <button class="btn btn-primary">Registrar plato</button>
    </div>
  </form>
</div>

templates/partials/menu/_navbar.html
<!--<header>-->
  <nav class="navbar navbar-expand-mg fixed-top navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('home.go_home')}}">
        <img
          src="{{url_for('static', filename='assets/logo/logo.svg')}}"
          alt=""
          width="30"
          height="24"
          class="d-inline-block align-text-top"
        />
        Restaurante
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Orden</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('user.show_users')}}"
              >Usuario</a
            >
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              Menú
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <a class="dropdown-item" href="{{url_for('menu.list_menu')}}"
                  >Lista Menú</a
                >
              </li>
              <li>
                <a
                  class="dropdown-item"
                  href="{{url_for('menu.register_plate')}}"
                  >Registrar Plato</a
                >
              </li>
              <li>
                <a class="dropdown-item" href="{{url_for('menu.show_plates')}}"
                  >Editar/Eliminar Platos</a
                >
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Acerca De</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('user.logout')}}">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<!--</header>-->

templates/partials/menu/_updateForm.html
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="mb-3">
      <div class="mt-5">
        <form action="/menu/update_plate/{{plate.id}}" method="post" class="card">
          <div class="card-body p4">
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Nombre de plato</label>
              <input type="text" name="name" placeholder="Write a name plate" class="form-control" id="exampleFormControlInput1 validationDefault01" value="{{plate.name}}" required/>
            </div>
            <div class="mb-3">
               <label for="exampleFormControlInput1" class="form-label">Precio de plato</label>
               <input type="text" name="price" placeholder="Write a price" class="form-control" id="exampleFormControlInput1 validationDefault05" pattern="[0-9]+" value="{{plate.price}}" required />
            </div>
            <div class="mb-3">
              <label for="exampleFormControlTextarea1" class="form-label">Descripción del producto</label>
               <input type="text" name="description" placeholder="Write a description" class="form-control" id="exampleFormControlInput1 validationDefault01" value="{{plate.description}}" />
            </div>
            <button class="btn btn-primary">Actualizar</button>
          </div>
        </form>
      </div>
    </div>
    </div>
  </div> 

templates/partials/messages/_messages.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {%for message in messages %}
      <div class="alert alert-success alert-dismissible fade show card-body" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}